# A sample Gemfile
source "http://rubygems.org"

gem 'thin'
gem 'sinatra'
gem 'haml'
gem 'json'
gem 'sequel'
gem 'sinatra-sequel'
gem 'sqlite3'
gem 'progressbar'

group :development do
  gem 'shotgun'
  gem 'foreman'
end