#!/bin/bash

start() {
  PATH="/home/ubuntu/.rbenv/bin:$PATH" && eval "$(rbenv init -)" && cd /home/ubuntu/challenge && bundle exec thin start -d -p 80 -e development
}

stop() {
  PATH="/home/ubuntu/.rbenv/bin:$PATH" && eval "$(rbenv init -)" && cd /home/ubuntu/challenge && bundle exec thin stop
}

restart() {
	PATH="/home/ubuntu/.rbenv/bin:$PATH" && eval "$(rbenv init -)" && cd /home/ubuntu/challenge && bundle exec thin restart
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
		restart
    ;;
  *)
    echo "Usage: {start|stop|restart}"
    exit 1
    ;;
esac

exit $?